"theme-addhen" :
  use : "theme"

"date_format": "%b %d, %Y"

production_url: 'http://www.addhen.org'

widgets :

  analytics :
    use : google
    # -- tracking code for google analytics --
    tracking_id : 'UA-1300221-1'
    domain_name : 'addhen.org'
    enable_demographics : true